version: "3"

services:
  pro-server:
    image: docker.pkg.github.com/laravel-pro/forum-server/pro-server:latest
    env_file: .env
    ports:
      - "8000:80"
    depends_on:
      - "mysql-server"
    environment:
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: mysql-server
      DB_PORT: 3306
      DB_DATABASE: e2e_test
      DB_USERNAME: root
      DB_PASSWORD:

  mysql-server:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "127.0.0.1:13306:3306"
    environment:
      MYSQL_DATABASE: e2e_test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
